// web/src/features/users/UserPage.tsx
import { useState } from 'react';
import { Link, useParams } from 'react-router';
import type { GroupData } from '../../api/admin';
import { ApiError } from '../../api/client';
import { errorText } from '../../api/errors';
import {
  Avatar,
  buttonClasses,
  Card,
  CardHeader,
  Chip,
  ConfirmDialog,
  EmptyState,
  ErrorState,
  formatDate,
  formatDateTime,
  formatNumber,
  formatRelative,
  Icon,
  LoadingIndicator,
  PageHeader,
  Stat,
  Switch,
  Table,
  useSnackbars,
} from '../../ui';
import { RestrictionsTable } from '../../shared/RestrictionsTable';
import { useModeratorRole, useUser } from './api';
import { RoleBadges } from './roles';
import type { AdminUserDetail } from './types';
import styles from './UserPage.module.css';

function BackLink() {
  return (
    <Link to="/admin/users" className={buttonClasses({ variant: 'text', size: 'small' })}>
      <Icon name="arrow_back" size={18} />
      Пользователи
    </Link>
  );
}

export function UserPage() {
  const isu = Number(useParams().isu);
  const user = useUser(isu);

  if (user.isPending) return <LoadingIndicator label="Загружаем пользователя" />;
  if (user.isError) {
    const missing = user.error instanceof ApiError && user.error.code === 'not_found';
    return (
      <div className={styles.page}>
        <BackLink />
        <Card>
          {missing ? (
            <EmptyState
              icon="person_off"
              title="Пользователь не найден"
              description="Проверьте номер ИСУ."
            />
          ) : (
            <ErrorState
              title="Не удалось загрузить пользователя"
              description={errorText(user.error, 'Попробуйте ещё раз.')}
              onRetry={() => void user.refetch()}
              retrying={user.isFetching}
            />
          )}
        </Card>
      </div>
    );
  }
  return <UserView detail={user.data} />;
}

function groupLine({ name, course, facultyShortName }: GroupData): string {
  return [name, course > 0 ? `${course} курс` : null, facultyShortName].filter(Boolean).join(' · ');
}

function UserView({ detail }: { detail: AdminUserDetail }) {
  const { user } = detail;
  const current = user.groups[0];
  return (
    <div className={styles.page}>
      <BackLink />
      <section aria-labelledby="user-name">
        <PageHeader
          titleId="user-name"
          leading={<Avatar name={user.name} src={user.pictureUrl} size={80} decorative />}
          title={user.name}
          description={`ИСУ ${user.isu}${current ? ` · ${groupLine(current)}` : ''}`}
          actions={<RoleBadges roles={detail.roles} />}
        />
      </section>

      <Card as="section" aria-labelledby="user-access">
        <CardHeader title={<span id="user-access">Доступ</span>} />
        <ModeratorSwitch detail={detail} />
      </Card>

      <div className={styles.stats}>
        <Stat
          icon="schedule"
          label="Последняя активность"
          value={detail.lastSeen ? formatRelative(detail.lastSeen) : '—'}
          caption={detail.lastSeen ? formatDateTime(detail.lastSeen) : 'Нет данных'}
        />
        <Stat icon="event" label="Регистрация" value={formatDate(detail.createdAt)} />
        <Stat icon="group" label="Друзья" value={formatNumber(detail.friendsCount)} />
        <Stat icon="link" label="Ссылки" value={formatNumber(detail.linksCount)} />
      </div>

      <div className={styles.columns}>
        <Card as="section" aria-labelledby="user-devices">
          <CardHeader title={<span id="user-devices">Устройства</span>} />
          <Table
            caption="Устройства"
            columns={[
              {
                key: 'name',
                header: 'Устройство',
                render: (device) => (
                  <span className={styles.device}>
                    <Icon name="smartphone" size={20} />
                    {device.name}
                  </span>
                ),
              },
              {
                key: 'lastLogin',
                header: 'Последний вход',
                align: 'end',
                render: (device) => formatDateTime(device.lastLogin),
              },
            ]}
            rows={detail.devices}
            rowKey={(device) => `${device.name}-${device.lastLogin}`}
            bleed
            empty={{ icon: 'mobile_off', title: 'Нет устройств' }}
          />
        </Card>
        <Card as="section" aria-labelledby="user-groups">
          <CardHeader
            title={<span id="user-groups">Группы</span>}
            subtitle="Все группы, которые были у пользователя"
          />
          {detail.groups.length === 0 ? (
            <p className="m3-muted">Групп нет</p>
          ) : (
            <ul className={styles.groups}>
              {detail.groups.map((group) => (
                <li key={group.name}>
                  <Chip icon="school">{groupLine(group)}</Chip>
                </li>
              ))}
            </ul>
          )}
        </Card>
      </div>

      <Card as="section" aria-labelledby="user-restrictions">
        <CardHeader title={<span id="user-restrictions">Ограничения</span>} />
        <RestrictionsTable
          caption="Ограничения пользователя"
          rows={detail.restrictions}
          showUser={false}
          bleed
          empty={{ title: 'Ограничений не было' }}
        />
      </Card>
    </div>
  );
}

function ModeratorSwitch({ detail }: { detail: AdminUserDetail }) {
  const snackbars = useSnackbars();
  const role = useModeratorRole(detail.user.isu);
  const [confirming, setConfirming] = useState<boolean | null>(null);
  const isAdmin = detail.roles.includes('ADMIN');
  const isModerator = detail.roles.includes('MODERATOR');
  const name = detail.user.name;

  const apply = () => {
    if (confirming === null) return;
    const grant = confirming;
    role.mutate(grant, {
      onSuccess: () => {
        setConfirming(null);
        snackbars.show(grant ? `${name} теперь модератор` : 'Роль модератора снята');
      },
      onError: (error) => snackbars.error(errorText(error, 'Не удалось изменить роль')),
    });
  };

  return (
    <div>
      <Switch
        label="Модератор"
        description={
          isAdmin ? 'Администратор уже может всё' : 'Решает заявки и ограничивает авторов'
        }
        checked={isAdmin || isModerator}
        disabled={isAdmin || role.isPending}
        onChange={setConfirming}
      />
      <ConfirmDialog
        open={confirming !== null}
        onClose={() => setConfirming(null)}
        onConfirm={apply}
        loading={role.isPending}
        title={confirming ? 'Назначить модератором?' : 'Снять роль модератора?'}
        description={
          confirming
            ? `${name} сможет решать заявки и ограничивать авторов.`
            : `${name} больше не сможет модерировать ссылки.`
        }
        confirmLabel={confirming ? 'Назначить' : 'Снять роль'}
        danger={confirming === false}
      />
    </div>
  );
}

// web/src/features/users/UserPage.svelte
<script lang="ts">
  import {
    ConfirmDialog,
    EmptyState,
    forget,
    Icon,
    LoadingIndicator,
    PageHeader,
    snackbars,
  } from '@alllexey/ui';
  import { api, ApiError } from '../../api/client';
  import { errorText } from '../../api/errors';
  import { formatDate, formatDateTime, formatNumber, formatRelative } from '../../lib/format';
  import LoadError from '../../lib/LoadError.svelte';
  import { Resource } from '../../lib/resource.svelte';
  import { href, router } from '../../lib/router.svelte';
  import type { Role } from '../../lib/session.svelte';
  import {
    CAPABILITIES,
    groupLine,
    platformCounts,
    platformLabel,
    restrictionState,
  } from './labels';
  import ModeratorSwitch from './ModeratorSwitch.svelte';
  import RoleBadges from './RoleBadges.svelte';
  import type { AdminRestriction, AdminUserDetail } from './types';

  // One user for the admin: access, activity, devices with their platform, groups and restrictions.
  const isu = router.route.name === 'user' ? router.route.isu : 0;
  const path = `/api/admin/users/${isu}`;
  const user = new Resource(path, () => api.get<AdminUserDetail>(path));
  void user.load();

  const missing = $derived(user.error instanceof ApiError && user.error.code === 'not_found');

  function rolesChanged(roles: Role[]) {
    if (user.data) user.data = { ...user.data, roles };
    // The list shows roles, the audit records the change.
    forget('/api/admin/users');
    forget('/api/admin/audit');
  }

  let revoking = $state<AdminRestriction | null>(null);
  async function revoke() {
    const restriction = revoking;
    revoking = null;
    if (!restriction) return;
    try {
      await api.post<null>(`/api/admin/moderation/restrictions/${restriction.id}/revoke`);
      snackbars.show('Ограничение снято');
      forget('/api/admin/moderation');
      forget(path);
      await user.load();
    } catch (error) {
      snackbars.error(errorText(error, 'Не удалось снять ограничение'));
    }
  }
</script>

<a class="m3-btn text back" href={href('/admin/users')}>
  <Icon name="arrow_back" size={18} />
  Пользователи
</a>

{#if user.data}
  {@const detail = user.data}
  {@const current = detail.user.groups[0]}
  <div class="head">
    <PageHeader
      title={detail.user.name}
      text={`ИСУ ${detail.user.isu}${current ? ` · ${groupLine(current)}` : ''}`}
    >
      {#snippet actions()}<RoleBadges roles={detail.roles} />{/snippet}
    </PageHeader>
  </div>

  <div class="layout">
    <section class="m3-card" aria-labelledby="user-access">
      <h2 id="user-access" class="m3-section-title">Доступ</h2>
      <ModeratorSwitch
        isu={detail.user.isu}
        name={detail.user.name}
        roles={detail.roles}
        onchanged={rolesChanged}
      />
    </section>

    <dl class="stats">
      <div class="m3-card">
        <dt>Последняя активность</dt>
        <dd>{detail.lastSeen ? formatRelative(detail.lastSeen) : '—'}</dd>
        {#if detail.lastSeen}<dd class="m3-muted caption">
            {formatDateTime(detail.lastSeen)}
          </dd>{/if}
      </div>
      <div class="m3-card">
        <dt>Регистрация</dt>
        <dd>{formatDate(detail.createdAt)}</dd>
      </div>
      <div class="m3-card">
        <dt>Друзья</dt>
        <dd class="m3-num">{formatNumber(detail.friendsCount)}</dd>
      </div>
      <div class="m3-card">
        <dt>Ссылки</dt>
        <dd class="m3-num">{formatNumber(detail.linksCount)}</dd>
      </div>
    </dl>

    <div class="columns">
      <section class="m3-card" aria-labelledby="user-devices">
        <h2 id="user-devices" class="m3-section-title">Устройства</h2>
        {#if detail.devices.length === 0}
          <p class="m3-muted">Нет устройств</p>
        {:else}
          <p class="m3-muted counts">{platformCounts(detail.devices)}</p>
          <ul class="m3-list divided plain" aria-label="Устройства">
            {#each detail.devices as device, index (`${device.name}-${device.lastLogin}-${index}`)}
              <li class="m3-list-item">
                <span class="lead"><Icon name="smartphone" /></span>
                <span class="main">
                  <span class="headline">{device.name}</span>
                  <span class="support">
                    {platformLabel(device)}{device.appVersion
                      ? ` · версия ${device.appVersion}`
                      : ''}
                  </span>
                </span>
                <span class="trail">{formatDateTime(device.lastLogin)}</span>
              </li>
            {/each}
          </ul>
        {/if}
      </section>

      <section class="m3-card" aria-labelledby="user-groups">
        <h2 id="user-groups" class="m3-section-title">Группы</h2>
        {#if detail.groups.length === 0}
          <p class="m3-muted">Групп нет</p>
        {:else}
          <ul class="m3-list plain">
            {#each detail.groups as group (group.name)}
              <li class="m3-list-item">
                <span class="lead"><Icon name="school" /></span>
                <span class="main"><span class="headline">{groupLine(group)}</span></span>
              </li>
            {/each}
          </ul>
        {/if}
      </section>
    </div>

    <section class="m3-card" aria-labelledby="user-restrictions">
      <h2 id="user-restrictions" class="m3-section-title">Ограничения</h2>
      {#if detail.restrictions.length === 0}
        <p class="m3-muted">Ограничений не было</p>
      {:else}
        <ul class="m3-list divided plain" aria-label="Ограничения пользователя">
          {#each detail.restrictions as restriction (restriction.id)}
            {@const state = restrictionState(restriction)}
            {@const end = restriction.revokedAt ?? restriction.expiresAt}
            <li class="m3-list-item restriction">
              <span class="lead"><Icon name="block" /></span>
              <span class="main">
                <span class="headline">{CAPABILITIES[restriction.capability]}</span>
                <span class="support">{restriction.reason}</span>
                <span class="support">
                  {end
                    ? `${formatDate(restriction.startsAt)} — ${formatDate(end)}`
                    : `с ${formatDate(restriction.startsAt)}, бессрочно`}
                </span>
              </span>
              <span class="trail actions">
                <span class="m3-pill {state.tone}">{state.label}</span>
                {#if restriction.active}
                  <button class="m3-btn text" onclick={() => (revoking = restriction)}>Снять</button
                  >
                {/if}
              </span>
            </li>
          {/each}
        </ul>
      {/if}
    </section>
  </div>

  {#if revoking}
    <ConfirmDialog
      title="Снять ограничение?"
      text={`${detail.user.name} снова сможет: ${CAPABILITIES[revoking.capability].toLowerCase()}.`}
      confirmLabel="Снять"
      onconfirm={revoke}
      oncancel={() => (revoking = null)}
    />
  {/if}
{:else if missing}
  <section class="m3-card">
    <EmptyState icon="person_off" title="Пользователь не найден" text="Проверьте номер ИСУ" />
  </section>
{:else if user.error}
  <section class="m3-card">
    <LoadError
      error={user.error}
      title="Не удалось загрузить пользователя"
      onretry={() => user.load()}
    />
  </section>
{:else}
  <div class="waiting"><LoadingIndicator label="Загружаем пользователя" /></div>
{/if}

<style>
  .back {
    margin: -8px 0 8px -12px;
  }
  /* A long name breaks inside a word rather than widening the page on a phone. */
  .head :global(h1) {
    overflow-wrap: anywhere;
  }
  .layout {
    display: grid;
    gap: 16px;
  }
  .stats {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(min(100%, 150px), 1fr));
    gap: 12px;
    margin: 0;
  }
  .stats dt {
    font: var(--md-label-large);
    color: var(--md-on-surface-variant);
  }
  .stats dd {
    margin: 4px 0 0;
    font: var(--md-headline-small);
  }
  .stats .caption {
    font: var(--md-body-small);
  }
  .columns {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(min(100%, 360px), 1fr));
    gap: 16px;
  }
  .plain {
    margin: 0 -16px;
    padding: 0;
    list-style: none;
  }
  .counts {
    margin: -4px 0 8px;
  }
  p {
    margin: 0;
  }
  .restriction .support {
    white-space: normal;
  }
  .actions {
    display: flex;
    align-items: center;
    flex-wrap: wrap;
    justify-content: flex-end;
    gap: 4px;
  }
  .waiting {
    display: grid;
    place-items: center;
    min-height: 40vh;
  }
  @media (max-width: 520px) {
    .restriction {
      flex-wrap: wrap;
    }
    .restriction .actions {
      width: 100%;
      justify-content: flex-start;
      padding-left: 40px;
    }
  }
</style>
