// web/src/features/moderation/CaseDetail.tsx
import { useState } from 'react';
import type { RestrictionCapability } from '../../api/admin';
import { ApiError } from '../../api/client';
import { errorText } from '../../api/errors';
import {
  Badge,
  Button,
  EmptyState,
  ErrorState,
  formatDateTime,
  IconButton,
  Kbd,
  LoadingIndicator,
  useSnackbars,
} from '../../ui';
import { useAccess } from '../auth/useSession';
import { useCase, useDecision } from './api';
import {
  AuthorSection,
  ChangesSection,
  DecisionsTimeline,
  LinkPreview,
  ReportsSection,
  ReviewChangesSection,
  ReviewPreview,
} from './CaseSections';
import { HideAllDialog, RejectDialog, RestrictDialog } from './DecisionDialogs';
import {
  CASE_STATUSES,
  doneText,
  LINK_REJECT_PRESETS,
  periodLabel,
  REASONS,
  REVIEW_REJECT_PRESETS,
} from './labels';
import styles from './CaseDetail.module.css';
import type { CaseTarget, DecisionRequest, ModerationCase, TargetType } from './types';
import { useShortcuts } from './useShortcuts';

type OpenDialog = 'reject' | 'restrict' | 'hideAll' | null;

interface TargetTexts {
  deleted: string;
  deletedNote: string;
  rejectTitle: string;
  rejectPresets: readonly string[];
  restriction: RestrictionCapability;
}

const TARGET_TEXTS: Record<TargetType, TargetTexts> = {
  SUBJECT_RESOURCE: {
    deleted: 'Ссылка удалена',
    deletedNote: 'Автор удалил ссылку; остались только решения.',
    rejectTitle: 'Отклонить ссылку',
    rejectPresets: LINK_REJECT_PRESETS,
    restriction: 'SUBMIT_RESOURCES',
  },
  TEACHER_REVIEW: {
    deleted: 'Отзыв удалён',
    deletedNote: 'Автор удалил отзыв; остались только решения.',
    rejectTitle: 'Отклонить отзыв',
    rejectPresets: REVIEW_REJECT_PRESETS,
    restriction: 'WRITE_REVIEWS',
  },
};

function targetTitle(target: CaseTarget): string {
  if (target.targetType === 'SUBJECT_RESOURCE') return target.link.subjectName;
  const { teacherName, teacherIsu } = target.review;
  return `${teacherName ?? 'Преподаватель'} · ИСУ ${teacherIsu}`;
}

function isHidden(target: CaseTarget): boolean {
  return target.targetType === 'SUBJECT_RESOURCE'
    ? target.link.status === 'HIDDEN'
    : target.review.hidden;
}

export interface CaseDetailProps {
  caseId: string;
  /** Shown on narrow screens, where the detail replaces the list. */
  onBack?: () => void;
  onDecided: (updated: ModerationCase) => void;
}

export function CaseDetail({ caseId, onBack, onDecided }: CaseDetailProps) {
  const query = useCase(caseId);

  if (query.isPending) return <DetailLoading />;
  if (query.isError) {
    const missing = query.error instanceof ApiError && query.error.code === 'not_found';
    return (
      <div className={styles.detail}>
        {onBack && <BackButton onBack={onBack} />}
        {missing ? (
          <EmptyState
            icon="search_off"
            title="Заявка не найдена"
            description="Возможно, её уже удалили."
          />
        ) : (
          <ErrorState
            title="Не удалось загрузить заявку"
            description={errorText(query.error, 'Попробуйте ещё раз.')}
            onRetry={() => void query.refetch()}
            retrying={query.isFetching}
          />
        )}
      </div>
    );
  }
  // A new key per case resets dialogs and the pending decision when the selection moves.
  return <CaseView key={query.data.id} data={query.data} onBack={onBack} onDecided={onDecided} />;
}

function BackButton({ onBack }: { onBack: () => void }) {
  return <IconButton icon="arrow_back" label="К списку" className={styles.back} onClick={onBack} />;
}

function CaseView({
  data,
  onBack,
  onDecided,
}: {
  data: ModerationCase;
  onBack?: () => void;
  onDecided: (updated: ModerationCase) => void;
}) {
  const canOpenProfile = useAccess('admin');
  const snackbars = useSnackbars();
  const decision = useDecision(data.id);
  const [dialog, setDialog] = useState<OpenDialog>(null);
  const target = data.target;
  const texts = TARGET_TEXTS[data.targetType];
  const open = data.status === 'OPEN' && target !== null;

  const decide = (request: DecisionRequest) => {
    decision.mutate(request, {
      onSuccess: (updated) => {
        setDialog(null);
        snackbars.show(doneText(request.action, data.targetType));
        onDecided(updated);
      },
      onError: (error) =>
        snackbars.error(
          errorText(error, 'Не удалось сохранить решение', {
            business_rule_violation: 'Заявка уже закрыта',
            invalid_request_data: 'Проверьте причину и срок',
          }),
        ),
    });
  };

  useShortcuts(
    {
      KeyA: () => decide({ action: 'APPROVE' }),
      KeyR: () => setDialog('reject'),
    },
    open && !decision.isPending && dialog === null,
  );

  const reason = REASONS[data.reason];
  const status = CASE_STATUSES[data.status];
  return (
    <article className={styles.detail} aria-labelledby="case-title">
      <header className={styles.header}>
        {onBack && <BackButton onBack={onBack} />}
        <div className={styles.headerText}>
          <div className={styles.badges}>
            <Badge tone={reason.tone} icon={reason.icon}>
              {reason.label}
            </Badge>
            <Badge tone={status.tone}>{status.label}</Badge>
            <span className={styles.muted}>с {formatDateTime(data.openedAt)}</span>
          </div>
          <h2 id="case-title" className={styles.title}>
            {target ? targetTitle(target) : texts.deleted}
          </h2>
          {target?.targetType === 'SUBJECT_RESOURCE' && (
            <p className={styles.muted}>{periodLabel(target.link.periodKey)}</p>
          )}
        </div>
      </header>

      {target ? (
        <>
          <CaseActions
            open={open}
            target={target}
            saving={decision.isPending}
            pendingAction={decision.isPending ? decision.variables.action : null}
            onDecide={decide}
            onOpenDialog={setDialog}
          />
          {target.targetType === 'SUBJECT_RESOURCE' ? (
            <>
              <LinkPreview target={target} />
              <ChangesSection target={target} />
            </>
          ) : (
            <>
              <ReviewPreview target={target} />
              <ReviewChangesSection target={target} />
            </>
          )}
          <AuthorSection
            author={target.author}
            submitterHistory={target.submitterHistory}
            canOpenProfile={canOpenProfile}
          />
          <ReportsSection reports={target.reports} />
        </>
      ) : (
        <p className={styles.note}>{texts.deletedNote}</p>
      )}
      <DecisionsTimeline decisions={data.decisions} />

      {target && dialog === 'reject' && (
        <RejectDialog
          open
          onClose={() => setDialog(null)}
          onSubmit={decide}
          saving={decision.isPending}
          title={texts.rejectTitle}
          presets={texts.rejectPresets}
        />
      )}
      {target && dialog === 'restrict' && (
        <RestrictDialog
          open
          onClose={() => setDialog(null)}
          onSubmit={decide}
          saving={decision.isPending}
          authorName={target.author.name}
          defaultCapability={texts.restriction}
        />
      )}
      {target && dialog === 'hideAll' && (
        <HideAllDialog
          open
          onClose={() => setDialog(null)}
          onSubmit={decide}
          saving={decision.isPending}
          authorName={target.author.name}
          targetType={data.targetType}
        />
      )}
    </article>
  );
}

function CaseActions({
  open,
  target,
  saving,
  pendingAction,
  onDecide,
  onOpenDialog,
}: {
  open: boolean;
  target: CaseTarget;
  saving: boolean;
  pendingAction: DecisionRequest['action'] | null;
  onDecide: (request: DecisionRequest) => void;
  onOpenDialog: (dialog: OpenDialog) => void;
}) {
  const hidden = isHidden(target);
  const restore = (
    <Button
      variant={open ? 'text' : 'tonal'}
      icon="visibility"
      loading={pendingAction === 'RESTORE'}
      disabled={saving}
      onClick={() => onDecide({ action: 'RESTORE' })}
    >
      Вернуть
    </Button>
  );
  if (!open) {
    return hidden ? (
      <div className={styles.actions} role="group" aria-label="Действия">
        {restore}
      </div>
    ) : null;
  }
  return (
    <div className={styles.actions} role="group" aria-label="Действия">
      <div className={styles.mainActions}>
        <Button
          icon="check"
          loading={pendingAction === 'APPROVE'}
          disabled={saving}
          onClick={() => onDecide({ action: 'APPROVE' })}
          aria-keyshortcuts="A"
        >
          Одобрить
        </Button>
        <Button
          variant="tonal"
          danger
          icon="close"
          disabled={saving}
          onClick={() => onOpenDialog('reject')}
          aria-keyshortcuts="R"
        >
          Отклонить
        </Button>
      </div>
      <div className={styles.moreActions}>
        {hidden ? (
          restore
        ) : (
          <Button
            variant="text"
            icon="visibility_off"
            loading={pendingAction === 'HIDE'}
            disabled={saving}
            onClick={() => onDecide({ action: 'HIDE' })}
          >
            Скрыть
          </Button>
        )}
        {target.reports.length > 0 && (
          <Button
            variant="text"
            icon="flag"
            loading={pendingAction === 'DISMISS'}
            disabled={saving}
            onClick={() => onDecide({ action: 'DISMISS' })}
          >
            Отклонить жалобы
          </Button>
        )}
        <Button
          variant="text"
          icon="block"
          disabled={saving}
          onClick={() => onOpenDialog('restrict')}
        >
          Ограничить
        </Button>
        <Button
          variant="text"
          danger
          icon="hide_source"
          disabled={saving}
          onClick={() => onOpenDialog('hideAll')}
        >
          Скрыть всё у автора
        </Button>
      </div>
    </div>
  );
}

export function ShortcutHint() {
  return (
    <p className={styles.hint}>
      <span>
        <Kbd>J</Kbd> <Kbd>K</Kbd> следующая и предыдущая
      </span>
      <span>
        <Kbd>A</Kbd> одобрить
      </span>
      <span>
        <Kbd>R</Kbd> отклонить
      </span>
    </p>
  );
}

function DetailLoading() {
  return <LoadingIndicator label="Загружаем заявку" />;
}

// web/src/features/moderation/CaseDetail.svelte
<script lang="ts">
  import { ConfirmDialog, EmptyState, Icon, Loadable, Resource, snackbars } from '@alllexey/ui';
  import { ApiError } from '../../api/client';
  import { errorText } from '../../api/errors';
  import LoadError from '../../lib/LoadError.svelte';
  import { hasAccess, session } from '../../lib/session.svelte';
  import { caseKey, decide, fetchCase } from './api';
  import AuthorSection from './AuthorSection.svelte';
  import CaseChanges from './CaseChanges.svelte';
  import CaseHistory from './CaseHistory.svelte';
  import { formatDateTime, formatRelative } from './format';
  import { CASE_STATUSES, doneText, periodLabel, REASONS, TARGET_TEXTS } from './labels';
  import LinkPreview from './LinkPreview.svelte';
  import RejectDialog from './RejectDialog.svelte';
  import RestrictDialog from './RestrictDialog.svelte';
  import ReviewPreview from './ReviewPreview.svelte';
  import { shortcuts } from './shortcuts.svelte';
  import type { CaseTarget, DecisionRequest, ModerationAction, ModerationCase } from './types';

  // One case; the page mounts a new instance per case, so dialogs and a pending decision never leak
  // into the next one. `onback` is given on phones, where the detail replaces the list.
  let {
    caseId,
    onback,
    ondecided,
  }: {
    caseId: string;
    onback?: () => void;
    ondecided: (updated: ModerationCase) => void;
  } = $props();

  // svelte-ignore state_referenced_locally
  const detail = new Resource(caseKey(caseId), () => fetchCase(caseId));
  void detail.load();

  let dialog = $state<'reject' | 'restrict' | 'hideAll' | null>(null);
  let pending = $state<ModerationAction | null>(null);

  const data = $derived(detail.data);
  const target = $derived(data?.target ?? null);
  const texts = $derived(data ? TARGET_TEXTS[data.targetType] : null);
  const open = $derived(data?.status === 'OPEN' && target !== null);
  const hidden = $derived(isHidden(target));
  const canOpenProfile = $derived(hasAccess(session.user, 'admin'));
  const missing = $derived(detail.error instanceof ApiError && detail.error.code === 'not_found');

  function isHidden(value: CaseTarget | null): boolean {
    if (!value) return false;
    return value.targetType === 'SUBJECT_RESOURCE'
      ? value.link.status === 'HIDDEN'
      : value.review.hidden;
  }

  function titleOf(value: CaseTarget): string {
    if (value.targetType === 'SUBJECT_RESOURCE') return value.link.subjectName;
    return `${value.review.teacherName ?? 'Преподаватель'} · ИСУ ${value.review.teacherIsu}`;
  }

  async function submit(request: DecisionRequest) {
    if (pending || !data) return;
    pending = request.action;
    try {
      const updated = await decide(data.id, request);
      detail.data = updated;
      dialog = null;
      snackbars.show(doneText(request.action, data.targetType));
      ondecided(updated);
    } catch (error) {
      snackbars.error(
        errorText(error, 'Не удалось сохранить решение', {
          business_rule_violation: 'Заявка уже закрыта',
          invalid_request_data: 'Проверьте причину и срок',
        }),
      );
      // A case closed by someone else: show its current state.
      void detail.load();
    } finally {
      pending = null;
    }
  }

  shortcuts(() =>
    open && !pending && !dialog
      ? { KeyA: () => void submit({ action: 'APPROVE' }), KeyR: () => (dialog = 'reject') }
      : {},
  );
</script>

<div class="detail">
  {#if !data && onback}
    <button class="m3-icon-btn back" aria-label="К списку" onclick={onback}>
      <Icon name="arrow_back" />
    </button>
  {/if}
  <Loadable resource={detail} loadingLabel="Загружаем заявку">
    {#snippet children(data)}
      {@const reason = REASONS[data.reason]}
      {@const status = CASE_STATUSES[data.status]}
      <article class="case" aria-labelledby="case-title">
        <header class="head">
          {#if onback}
            <button class="m3-icon-btn back" aria-label="К списку" onclick={onback}>
              <Icon name="arrow_back" />
            </button>
          {/if}
          <div class="head-text">
            <div class="badges">
              <span class="m3-pill {reason.tone}">{reason.label}</span>
              {#if data.status !== 'OPEN'}<span class="m3-pill {status.tone}">{status.label}</span
                >{/if}
              <span class="m3-body-small m3-muted" title={formatDateTime(data.openedAt)}>
                открыта {formatRelative(data.openedAt)}
              </span>
            </div>
            <h2 id="case-title" class="title">{target ? titleOf(target) : texts?.deleted}</h2>
            {#if target?.targetType === 'SUBJECT_RESOURCE'}
              <p class="m3-muted period">{periodLabel(target.link.periodKey)}</p>
            {/if}
          </div>
        </header>

        {#if target && texts}
          {#if open}
            <div class="actions" role="group" aria-label="Действия">
              <button
                class="m3-btn"
                disabled={pending !== null}
                aria-keyshortcuts="A"
                onclick={() => submit({ action: 'APPROVE' })}
              >
                <Icon name="check" />Одобрить
              </button>
              <button
                class="m3-btn danger-tonal"
                disabled={pending !== null}
                aria-keyshortcuts="R"
                onclick={() => (dialog = 'reject')}
              >
                <Icon name="close" />Отклонить
              </button>
              {#if hidden}
                <button
                  class="m3-btn text"
                  disabled={pending !== null}
                  onclick={() => submit({ action: 'RESTORE' })}
                >
                  <Icon name="visibility" />Вернуть
                </button>
              {:else}
                <button
                  class="m3-btn text"
                  disabled={pending !== null}
                  onclick={() => submit({ action: 'HIDE' })}
                >
                  <Icon name="visibility_off" />Скрыть
                </button>
              {/if}
              {#if target.reports.length > 0}
                <button
                  class="m3-btn text"
                  disabled={pending !== null}
                  onclick={() => submit({ action: 'DISMISS' })}
                >
                  <Icon name="flag" />Отклонить жалобы
                </button>
              {/if}
              <button
                class="m3-btn text"
                disabled={pending !== null}
                onclick={() => (dialog = 'restrict')}
              >
                <Icon name="block" />Ограничить
              </button>
              <button
                class="m3-btn text error"
                disabled={pending !== null}
                onclick={() => (dialog = 'hideAll')}
              >
                <Icon name="hide_source" />Скрыть всё у автора
              </button>
            </div>
          {:else if hidden}
            <div class="actions" role="group" aria-label="Действия">
              <button
                class="m3-btn tonal"
                disabled={pending !== null}
                onclick={() => submit({ action: 'RESTORE' })}
              >
                <Icon name="visibility" />Вернуть
              </button>
            </div>
          {/if}

          {#if target.targetType === 'SUBJECT_RESOURCE'}
            <LinkPreview {target} />
          {:else}
            <ReviewPreview {target} />
          {/if}
          <CaseChanges {target} />
          <AuthorSection
            author={target.author}
            history={target.submitterHistory}
            {canOpenProfile}
          />
        {:else if texts}
          <p class="mod-note">{texts.deletedNote}</p>
        {/if}
        <CaseHistory reports={target?.reports ?? null} decisions={data.decisions} />
      </article>

      {#if target && texts && dialog === 'reject'}
        <RejectDialog
          title={texts.rejectTitle}
          presets={texts.rejectPresets}
          saving={pending !== null}
          onsubmit={submit}
          onclose={() => (dialog = null)}
        />
      {:else if target && texts && dialog === 'restrict'}
        <RestrictDialog
          authorName={target.author.name}
          defaultCapability={texts.restriction}
          saving={pending !== null}
          onsubmit={submit}
          onclose={() => (dialog = null)}
        />
      {:else if target && texts && dialog === 'hideAll'}
        <ConfirmDialog
          title={texts.hideAllTitle}
          text={texts.hideAllText(target.author.name)}
          confirmLabel="Скрыть всё"
          danger
          requireText={target.author.name}
          onconfirm={() => submit({ action: 'HIDE_ALL_BY_USER' })}
          oncancel={() => !pending && (dialog = null)}
        />
      {/if}
    {/snippet}
    {#snippet failed(error)}
      {#if missing}
        <EmptyState icon="search_off" title="Заявка не найдена" text="Возможно, её уже удалили." />
      {:else}
        <LoadError {error} title="Не удалось загрузить заявку" onretry={() => detail.load()} />
      {/if}
    {/snippet}
  </Loadable>
</div>

<style>
  .detail {
    display: grid;
    gap: 20px;
  }
  .case {
    display: grid;
    gap: 24px;
    min-width: 0;
  }
  .head {
    display: flex;
    align-items: flex-start;
    gap: 8px;
  }
  .back {
    flex: none;
    margin: -4px 0 0 -8px;
  }
  .head-text {
    flex: 1;
    min-width: 0;
    display: grid;
    gap: 8px;
  }
  .badges {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 8px;
  }
  .title {
    font: var(--md-headline-small);
    overflow-wrap: anywhere;
  }
  .period {
    margin: -4px 0 0;
  }
  .actions {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
  }
  .m3-btn.error {
    color: var(--md-error);
  }
</style>
