// web-next/src/features/audit/AuditPage.svelte
<script lang="ts">
  import { EmptyState, Icon, LoadingIndicator, LoadingOverlay, PageHeader } from '@alllexey/ui';
  import { api } from '../../api/client';
  import { formatDateTime } from '../../lib/format';
  import LoadError from '../../lib/LoadError.svelte';
  import Pagination from '../../lib/Pagination.svelte';
  import { Resource } from '../../lib/resource.svelte';
  import { href, router } from '../../lib/router.svelte';
  import { ACTIONS, detailsOf, targetOf, type AuditEntry } from './labels';

  // Who changed or started what, newest first; `page` lives in the URL.
  const SIZE = 20;

  interface AuditPage {
    items: AuditEntry[];
    page: number;
    size: number;
    total: number;
  }

  const page = $derived(Math.max(0, Number(router.query.get('page')) || 0));
  const request = (p: number) => ({
    key: `/api/admin/audit?page=${p}&size=${SIZE}`,
    fetch: () => api.get<AuditPage>('/api/admin/audit', { query: { page: p, size: SIZE } }),
  });
  const audit = new Resource<AuditPage>(request(0).key, request(0).fetch);
  $effect(() => {
    const next = request(page);
    void audit.load(next.key, next.fetch);
  });
</script>

<PageHeader
  title="Журнал"
  text="Кто и когда менял роли, правила модерации, версию приложения и учётные данные или запускал синхронизацию и ИИ-сводки"
/>

{#if audit.data}
  {@const list = audit.data}
  <LoadingOverlay loading={audit.loading}>
    <section class="m3-card flush">
      {#if list.items.length === 0}
        <EmptyState icon="history" title="Записей пока нет" />
      {:else}
        <div class="m3-table" role="table" aria-label="Журнал">
          <div class="tr th" role="row">
            <span role="columnheader">Когда</span>
            <span role="columnheader">Кто</span>
            <span role="columnheader">Действие</span>
            <span role="columnheader">Объект</span>
            <span role="columnheader">Подробности</span>
          </div>
          {#each list.items as entry (entry.id)}
            {@const action = ACTIONS[entry.action]}
            {@const target = targetOf(entry.target)}
            {@const details = detailsOf(entry)}
            <div class="tr" role="row">
              <span role="cell" class="m3-num nowrap">{formatDateTime(entry.createdAt)}</span>
              <span role="cell" class="actor">
                <a class="link" href={href(`/admin/users/${entry.actorIsu}`)}>{entry.actorName}</a>
                <span class="m3-muted m3-body-small">ИСУ {entry.actorIsu}</span>
              </span>
              <span role="cell" class="action">
                <Icon name={action?.icon ?? 'history'} size={20} />
                <span>{action?.label ?? entry.action}</span>
                {#if details.platform}<span class="m3-pill neutral">{details.platform}</span>{/if}
              </span>
              <span role="cell">
                {#if target.kind === 'user'}
                  <a class="link" href={href(`/admin/users/${target.isu}`)}>ИСУ {target.isu}</a>
                {:else}
                  {target.text}
                {/if}
              </span>
              <span role="cell">
                {#if details.text}
                  <code class="m3-mono details">{details.text}</code>
                {:else}
                  <span class="m3-muted">—</span>
                {/if}
              </span>
            </div>
          {/each}
        </div>
      {/if}
      <Pagination
        {page}
        size={SIZE}
        total={list.total}
        onchange={(next) => router.setQuery({ page: next > 0 ? next : null })}
      />
    </section>
  </LoadingOverlay>
{:else if audit.error}
  <section class="m3-card">
    <LoadError
      error={audit.error}
      title="Не удалось загрузить журнал"
      onretry={() => audit.load()}
    />
  </section>
{:else}
  <div class="waiting"><LoadingIndicator label="Загружаем журнал" /></div>
{/if}

<style>
  .tr {
    grid-template-columns: 148px minmax(150px, 1fr) minmax(190px, 1.2fr) minmax(140px, 1fr) minmax(
        200px,
        1.6fr
      );
    min-width: 900px;
    align-items: start;
  }
  .nowrap {
    white-space: nowrap;
  }
  .actor {
    display: grid;
  }
  .action {
    display: flex;
    align-items: center;
    flex-wrap: wrap;
    gap: 8px;
  }
  .link {
    color: var(--md-primary);
    text-decoration: underline;
    text-underline-offset: 2px;
  }
  .details {
    overflow-wrap: anywhere;
  }
  .waiting {
    display: grid;
    place-items: center;
    min-height: 40vh;
  }
</style>

// web/src/features/audit/AuditPage.tsx
import { keepPreviousData, useQuery } from '@tanstack/react-query';
import { Link, useSearchParams } from 'react-router';
import { DEFAULT_PAGE_SIZE, type AdminPage } from '../../api/admin';
import { api } from '../../api/client';
import { errorText } from '../../api/errors';
import {
  ErrorState,
  formatDateTime,
  Icon,
  PageHeader,
  Pagination,
  Table,
  type TableColumn,
} from '../../ui';
import styles from './AuditPage.module.css';

/** `AdminAuditEntry`. */
export interface AuditEntry {
  id: string;
  action: string;
  target: string;
  details: string | null;
  createdAt: string;
  actorIsu: number;
  actorName: string;
}

const ACTIONS: Record<string, { label: string; icon: string }> = {
  ROLE_GRANTED: { label: 'Выдана роль', icon: 'person_add' },
  ROLE_REVOKED: { label: 'Снята роль', icon: 'person_remove' },
  MODERATION_SETTINGS_CHANGED: { label: 'Правила модерации', icon: 'tune' },
  APP_VERSION_CHANGED: { label: 'Версия приложения', icon: 'system_update' },
  REVIEWS_SYNC_STARTED: { label: 'Синхронизация отзывов', icon: 'sync' },
  SERVICE_CREDENTIAL_REPLACED: { label: 'Замена учётных данных', icon: 'key' },
};

const TARGETS: Record<string, string> = {
  'moderation-settings': 'Настройки модерации',
  'app-version': 'Версия приложения',
  'reviews-sync': 'Отзывы',
  'credential:MY_ITMO_REFRESH_TOKEN': 'My ITMO · refresh-токен',
  'credential:ISU_KEYCLOAK_IDENTITY': 'ИСУ · cookie KEYCLOAK_IDENTITY',
};

function Target({ target }: { target: string }) {
  const user = /^user:(\d+)$/.exec(target);
  if (user) return <Link to={`/admin/users/${user[1]}`}>ИСУ {user[1]}</Link>;
  return <>{TARGETS[target] ?? target}</>;
}

const COLUMNS: TableColumn<AuditEntry>[] = [
  {
    key: 'time',
    header: 'Когда',
    width: 160,
    render: (entry) => <span className={styles.nowrap}>{formatDateTime(entry.createdAt)}</span>,
  },
  {
    key: 'actor',
    header: 'Кто',
    render: (entry) => (
      <span className={styles.actor}>
        <Link to={`/admin/users/${entry.actorIsu}`}>{entry.actorName}</Link>
        <span className={styles.muted}>ИСУ {entry.actorIsu}</span>
      </span>
    ),
  },
  {
    key: 'action',
    header: 'Действие',
    render: (entry) => {
      const action = ACTIONS[entry.action];
      return (
        <span className={styles.action}>
          <Icon name={action?.icon ?? 'history'} size={20} />
          {action?.label ?? entry.action}
        </span>
      );
    },
  },
  { key: 'target', header: 'Объект', render: (entry) => <Target target={entry.target} /> },
  {
    key: 'details',
    header: 'Подробности',
    render: (entry) =>
      entry.details ? (
        <code className={styles.details}>{entry.details}</code>
      ) : (
        <span className={styles.muted}>—</span>
      ),
  },
];

export function AuditPage() {
  const [params, setParams] = useSearchParams();
  const page = Math.max(0, Number(params.get('page')) || 0);
  const audit = useQuery({
    queryKey: ['admin', 'audit', page],
    queryFn: ({ signal }) =>
      api.get<AdminPage<AuditEntry>>('/api/admin/audit', {
        query: { page, size: DEFAULT_PAGE_SIZE },
        signal,
      }),
    placeholderData: keepPreviousData,
  });

  return (
    <>
      <PageHeader
        title="Журнал"
        description="Роли, правила модерации, версия приложения, синхронизация отзывов и учётные данные: кто и когда менял или запускал"
      />
      {audit.isError ? (
        <ErrorState
          title="Не удалось загрузить журнал"
          description={errorText(audit.error, 'Попробуйте ещё раз.')}
          onRetry={() => void audit.refetch()}
          retrying={audit.isFetching}
        />
      ) : (
        <>
          <Table
            caption="Журнал"
            columns={COLUMNS}
            rows={audit.data?.items ?? []}
            rowKey={(entry) => entry.id}
            loading={audit.isPending}
            maxHeight="none"
            empty={{ icon: 'history', title: 'Записей пока нет' }}
          />
          {audit.data && (
            <Pagination
              page={page}
              size={DEFAULT_PAGE_SIZE}
              total={audit.data.total}
              onChange={(next) =>
                setParams(next > 0 ? { page: String(next) } : {}, { replace: false })
              }
            />
          )}
        </>
      )}
    </>
  );
}
