// web/src/ui/Avatar.tsx
import { useState } from 'react';
import styles from './Avatar.module.css';
import { cx } from './cx';
import { initialsOf } from './initials';
import { Shape } from './Shape';

export interface AvatarProps {
  name: string;
  src?: string | null;
  size?: 32 | 36 | 40 | 56 | 80;
  /** Hide from assistive technology when the name is already next to it. */
  decorative?: boolean;
  className?: string;
}

/** The photo when it loads, otherwise initials on the cookie shape of `@alllexey/ui`'s Account. */
export function Avatar({ name, src, size = 40, decorative = false, className }: AvatarProps) {
  const [failedSrc, setFailedSrc] = useState<string | null>(null);
  const a11y = decorative
    ? { 'aria-hidden': true as const }
    : { role: 'img' as const, 'aria-label': name };

  if (src && failedSrc !== src) {
    return (
      <img
        className={cx(styles.image, className)}
        src={src}
        alt=""
        width={size}
        height={size}
        referrerPolicy="no-referrer"
        onError={() => setFailedSrc(src)}
        {...a11y}
      />
    );
  }
  return (
    <span className={cx(styles.wrap, className)} {...a11y}>
      <Shape size={size} tone="tertiary">
        <span className={styles.initials} style={{ fontSize: Math.round(size * 0.4) }}>
          {initialsOf(name)}
        </span>
      </Shape>
    </span>
  );
}

// web/src/features/home/Avatar.svelte
<script lang="ts">
  import { Shape } from '@alllexey/ui';
  import { initialsOf } from './student';

  // The photo when it loads, otherwise initials on the cookie shape; decorative, the name is next to it.
  let { name, src, size = 40 }: { name: string; src: string | null; size?: number } = $props();
  let failed = $state<string | null>(null);
</script>

{#if src && failed !== src}
  <img
    class="photo"
    {src}
    alt=""
    width={size}
    height={size}
    referrerpolicy="no-referrer"
    aria-hidden="true"
    onerror={() => (failed = src)}
  />
{:else}
  <span class="initials" class:large={size >= 48} class:huge={size >= 72} aria-hidden="true">
    <Shape
      shape="cookie9"
      {size}
      color="var(--md-tertiary-container)"
      fg="var(--md-on-tertiary-container)"
    >
      {initialsOf(name)}
    </Shape>
  </span>
{/if}

<style>
  .photo {
    flex: none;
    border-radius: 50%;
    object-fit: cover;
  }
  .initials {
    flex: none;
    font: var(--md-label-large);
  }
  .initials.large {
    font: var(--md-title-medium);
  }
  .initials.huge {
    font: var(--md-headline-small);
  }
</style>
