// web/src/features/reviews/SummaryDialog.tsx
import { useState } from 'react';
import { errorText } from '../../api/errors';
import {
  Badge,
  Button,
  Chip,
  Dialog,
  formatDateTime,
  formatNumber,
  plural,
  useSnackbars,
} from '../../ui';
import { useAiSummaries, useRegenerateSummary, useSetSummaryHidden } from './api';
import {
  SUMMARY_CONFIDENCES,
  SUMMARY_LEVELS,
  SUMMARY_SCALE_VALUES,
  SUMMARY_SCALES,
  SUMMARY_STATUSES,
  summaryTagLabel,
} from './labels';
import styles from './ReviewsPage.module.css';
import type { TeacherSummary, TeacherSummaryRow } from './types';

/** The backend builds a summary from at least this many reviews. */
const MIN_REVIEWS = 3;

const ERRORS = {
  not_found: 'Сводка не найдена',
  business_rule_violation: 'Сейчас пересчитать нельзя',
};

export interface SummaryDialogProps {
  row: TeacherSummaryRow;
  onClose: () => void;
}

/** Texts come from the model and are shown as plain text only. */
export function SummaryDialog({ row: initial, onClose }: SummaryDialogProps) {
  const snackbars = useSnackbars();
  const state = useAiSummaries();
  const setHidden = useSetSummaryHidden();
  const regenerate = useRegenerateSummary();
  const [row, setRow] = useState(initial);
  const busy = setHidden.isPending || regenerate.isPending;
  const canRegenerate =
    state.data?.enabled === true && !row.hidden && row.inputCount >= MIN_REVIEWS;

  const toggleHidden = () =>
    setHidden.mutate(
      { isu: row.teacherIsu, hidden: !row.hidden },
      {
        onSuccess: setRow,
        onError: (error) =>
          snackbars.error(
            errorText(
              error,
              row.hidden ? 'Не удалось показать сводку' : 'Не удалось скрыть сводку',
              ERRORS,
            ),
          ),
      },
    );

  const requestRegeneration = () =>
    regenerate.mutate(row.teacherIsu, {
      onSuccess: (updated) => {
        setRow(updated);
        snackbars.show('Пересчёт запрошен');
      },
      onError: (error) =>
        snackbars.error(errorText(error, 'Не удалось пересчитать сводку', ERRORS)),
    });

  const status = SUMMARY_STATUSES[row.status];
  return (
    <Dialog
      open
      onClose={onClose}
      title={row.teacherName ?? `ИСУ ${row.teacherIsu}`}
      description={row.teacherName ? `ИСУ ${row.teacherIsu}` : undefined}
      size="large"
      actions={
        <>
          <Button variant="text" onClick={onClose}>
            Закрыть
          </Button>
          <Button
            variant="tonal"
            icon={row.hidden ? 'visibility' : 'visibility_off'}
            loading={setHidden.isPending}
            disabled={busy}
            onClick={toggleHidden}
          >
            {row.hidden ? 'Показать' : 'Скрыть'}
          </Button>
          <Button
            icon="refresh"
            loading={regenerate.isPending}
            disabled={busy || !canRegenerate}
            onClick={requestRegeneration}
          >
            Пересчитать
          </Button>
        </>
      }
    >
      <div className={styles.summary}>
        <p className={styles.state}>
          <Badge tone={status.tone}>{status.label}</Badge>
          <span>Отзывов сейчас: {formatNumber(row.inputCount)}</span>
          {row.hiddenAt && (
            <span>
              {row.hiddenByName ? `Кто скрыл: ${row.hiddenByName} · ` : 'Скрыта '}
              {formatDateTime(row.hiddenAt)}
            </span>
          )}
        </p>
        {row.lastError && (
          <p className={styles.state}>
            <code className={styles.error}>{row.lastError}</code>
            <span>
              Попыток: {formatNumber(row.attempts)}
              {row.lastAttemptAt && ` · ${formatDateTime(row.lastAttemptAt)}`}
            </span>
          </p>
        )}
        {row.summary ? (
          <SummaryContent summary={row.summary} />
        ) : (
          <p className="m3-muted">Сводки ещё нет</p>
        )}
      </div>
    </Dialog>
  );
}

function SummaryContent({ summary }: { summary: TeacherSummary }) {
  const count = summary.reviewCount;
  return (
    <>
      <p className="m3-muted">
        Сводка по {formatNumber(count)} {plural(count, ['отзыву', 'отзывам', 'отзывам'])} · ИИ ·{' '}
        {formatDateTime(summary.generatedAt)}
      </p>
      <p>
        Тон: {SUMMARY_LEVELS[summary.level]}
        <span className="m3-muted"> · уверенность {SUMMARY_CONFIDENCES[summary.confidence]}</span>
      </p>
      <p className={styles.text}>{summary.description}</p>
      <Points title="Плюсы" items={summary.pros} />
      <Points title="Минусы" items={summary.cons} />
      {summary.tags.length > 0 && (
        <ul className={styles.tags} aria-label="Теги">
          {summary.tags.map((tag) => (
            <li key={tag}>
              <Chip>{summaryTagLabel(tag)}</Chip>
            </li>
          ))}
        </ul>
      )}
      <dl className={styles.scales} aria-label="Шкалы">
        {summary.scales.map((scale) => (
          <div key={scale.kind}>
            <dt>{SUMMARY_SCALES[scale.kind]}</dt>
            <dd>
              {SUMMARY_SCALE_VALUES[scale.kind][scale.value]}
              {scale.reason && <span className="m3-muted"> · {scale.reason}</span>}
            </dd>
          </div>
        ))}
      </dl>
    </>
  );
}

function Points({ title, items }: { title: string; items: string[] }) {
  if (items.length === 0) return null;
  return (
    <section className={styles.points} aria-label={title}>
      <h3 className={styles.pointsTitle}>{title}</h3>
      <ul>
        {items.map((item) => (
          <li key={item} className={styles.text}>
            {item}
          </li>
        ))}
      </ul>
    </section>
  );
}

// web/src/features/reviews/SummaryDialog.svelte
<script lang="ts">
  import { Dialog, Icon, snackbars } from '@alllexey/ui';
  import { untrack } from 'svelte';
  import { errorText } from '../../api/errors';
  import { regenerateSummary, setSummaryHidden } from './api';
  import { formatDateTime, formatNumber, plural } from './format';
  import {
    SUMMARY_CONFIDENCES,
    SUMMARY_LEVELS,
    SUMMARY_SCALE_VALUES,
    SUMMARY_SCALES,
    SUMMARY_STATUSES,
    summaryTagLabel,
  } from './labels';
  import type { TeacherSummaryRow } from './types';

  // One teacher's summary. Texts come from the model and are rendered as text only: no HTML, no links.
  // Each change answers the updated row, which replaces the one the dialog started from.
  let {
    row: initial,
    enabled,
    onchanged,
    onclose,
  }: {
    row: TeacherSummaryRow;
    /** Summaries are on at the server. */
    enabled: boolean;
    onchanged: () => void;
    onclose: () => void;
  } = $props();

  /** The backend builds a summary from at least this many reviews. */
  const MIN_REVIEWS = 3;
  const ERRORS = {
    not_found: 'Сводка не найдена',
    business_rule_violation: 'Сейчас пересчитать нельзя',
  };

  let row = $state(untrack(() => initial));
  let busy = $state(false);
  const status = $derived(SUMMARY_STATUSES[row.status]);
  const canRegenerate = $derived(enabled && !row.hidden && row.inputCount >= MIN_REVIEWS);

  async function change(run: () => Promise<TeacherSummaryRow>, done: string, failed: string) {
    busy = true;
    try {
      row = await run();
      snackbars.show(done);
    } catch (error) {
      snackbars.error(errorText(error, failed, ERRORS));
    } finally {
      busy = false;
      onchanged();
    }
  }

  const toggleHidden = () =>
    row.hidden
      ? change(
          () => setSummaryHidden(row.teacherIsu, false),
          'Сводка показана',
          'Не удалось показать сводку',
        )
      : change(
          () => setSummaryHidden(row.teacherIsu, true),
          'Сводка скрыта',
          'Не удалось скрыть сводку',
        );

  const regenerate = () =>
    change(
      () => regenerateSummary(row.teacherIsu),
      'Пересчёт запрошен',
      'Не удалось пересчитать сводку',
    );
</script>

<Dialog
  title={row.teacherName ?? `ИСУ ${row.teacherIsu}`}
  text={row.teacherName ? `ИСУ ${row.teacherIsu}` : ''}
  wide
  {onclose}
>
  <div class="summary">
    <p class="line">
      <span class="m3-pill {status.pill}">{status.label}</span>
      <span class="m3-body-medium">Отзывов сейчас: {formatNumber(row.inputCount)}</span>
      {#if row.hiddenAt}
        <span class="m3-body-medium m3-muted">
          {row.hiddenByName ? `Скрыл ${row.hiddenByName}` : 'Скрыта'} · {formatDateTime(
            row.hiddenAt,
          )}
        </span>
      {/if}
    </p>
    {#if row.lastError}
      <p class="line">
        <code class="m3-mono m3-body-small error">{row.lastError}</code>
        <span class="m3-body-small m3-muted">
          Попыток: {formatNumber(row.attempts)}{row.lastAttemptAt
            ? ` · ${formatDateTime(row.lastAttemptAt)}`
            : ''}
        </span>
      </p>
    {/if}
    {#if row.summary}
      {@const summary = row.summary}
      <p class="m3-body-small m3-muted">
        Сводка по {formatNumber(summary.reviewCount)}
        {plural(summary.reviewCount, ['отзыву', 'отзывам', 'отзывам'])} · ИИ · {formatDateTime(
          summary.generatedAt,
        )}
      </p>
      <p class="m3-body-large">
        Тон: {SUMMARY_LEVELS[summary.level]}<span class="m3-muted">
          · уверенность {SUMMARY_CONFIDENCES[summary.confidence]}</span
        >
      </p>
      <p class="text">{summary.description}</p>
      {#each [{ title: 'Плюсы', items: summary.pros }, { title: 'Минусы', items: summary.cons }] as points (points.title)}
        {#if points.items.length > 0}
          <section aria-label={points.title}>
            <h3 class="m3-title-small">{points.title}</h3>
            <ul>
              {#each points.items as item, index (index)}<li class="text">{item}</li>{/each}
            </ul>
          </section>
        {/if}
      {/each}
      {#if summary.tags.length > 0}
        <ul class="tags" aria-label="Теги">
          {#each summary.tags as tag (tag)}<li class="m3-chip">{summaryTagLabel(tag)}</li>{/each}
        </ul>
      {/if}
      <dl class="scales" aria-label="Шкалы">
        {#each summary.scales as scale (scale.kind)}
          <div>
            <dt class="m3-label-large">{SUMMARY_SCALES[scale.kind]}</dt>
            <dd class="m3-body-medium">
              {SUMMARY_SCALE_VALUES[scale.kind][scale.value]}{#if scale.reason}<span
                  class="m3-muted text">{` · ${scale.reason}`}</span
                >{/if}
            </dd>
          </div>
        {/each}
      </dl>
    {:else}
      <p class="m3-muted">Сводки ещё нет</p>
    {/if}
  </div>
  {#snippet actions()}
    <button class="m3-btn text" onclick={onclose}>Закрыть</button>
    <button class="m3-btn tonal" onclick={toggleHidden} disabled={busy}>
      <Icon name={row.hidden ? 'visibility' : 'visibility_off'} />{row.hidden
        ? 'Показать'
        : 'Скрыть'}
    </button>
    <button class="m3-btn" onclick={regenerate} disabled={busy || !canRegenerate}>
      <Icon name="refresh" />Пересчитать
    </button>
  {/snippet}
</Dialog>

<style>
  .summary {
    display: grid;
    gap: 12px;
  }
  .summary p,
  h3,
  ul,
  dl {
    margin: 0;
  }
  .line {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 4px 12px;
  }
  .error {
    overflow-wrap: anywhere;
    color: var(--md-error);
  }
  .text {
    white-space: pre-line;
    overflow-wrap: anywhere;
  }
  section ul {
    display: grid;
    gap: 4px;
    margin-top: 4px;
    padding-left: 20px;
  }
  .tags {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
    padding: 0;
    list-style: none;
  }
  .scales {
    display: grid;
    gap: 8px;
  }
  dd {
    margin: 0;
  }
</style>
