// web/src/features/reviews/SummariesCard.svelte
<script lang="ts">
  import { ConfirmDialog, Icon, LoadingIndicator, snackbars, StatusShape } from '@alllexey/ui';
  import { errorText } from '../../api/errors';
  import LoadError from '../../lib/LoadError.svelte';
  import type { Resource } from '../../lib/resource.svelte';
  import { href } from '../../lib/router.svelte';
  import { startSummaries } from './api';
  import { formatDateTime, formatDay, formatNumber } from './format';
  import { RUN_OUTCOMES, RUN_TRIGGERS } from './labels';
  import type { AiSummariesState } from './types';

  // The night run and "Пересчитать всё"; the page polls the state while a run goes.
  let { summaries }: { summaries: Resource<AiSummariesState> } = $props();

  let confirming = $state(false);
  let starting = $state(false);

  async function start() {
    confirming = false;
    starting = true;
    try {
      summaries.data = await startSummaries();
    } catch (error) {
      snackbars.error(
        errorText(error, 'Не удалось запустить пересчёт', {
          business_rule_violation: 'Пересчёт уже идёт',
        }),
      );
      void summaries.load();
    } finally {
      starting = false;
    }
  }

  const health = $derived.by(() => {
    const state = summaries.data;
    if (!state) return null;
    if (!state.enabled) return { tone: 'off' as const, label: 'Выключены на сервере' };
    if (state.running) return { tone: 'warn' as const, label: 'Идёт пересчёт' };
    if (!state.lastOutcome) return { tone: 'off' as const, label: 'Ещё не запускался' };
    return RUN_OUTCOMES[state.lastOutcome];
  });
  const remaining = $derived(
    summaries.data ? Math.max(0, summaries.data.dailyBudget - summaries.data.budgetUsed) : 0,
  );
</script>

<section class="m3-card" aria-labelledby="reviews-ai">
  <header class="head">
    <div>
      <h2 class="m3-section-title" id="reviews-ai">ИИ-сводки</h2>
      {#if summaries.data?.model}
        <p class="m3-body-medium m3-muted model">Gemini · {summaries.data.model}</p>
      {/if}
    </div>
    {#if summaries.data}
      <button
        class="m3-btn tonal"
        onclick={() => (confirming = true)}
        disabled={!summaries.data.enabled ||
          summaries.data.keyStatus === 'MISSING' ||
          summaries.data.running ||
          starting}
      >
        Пересчитать всё
      </button>
    {/if}
  </header>
  {#if summaries.data}
    {@const state = summaries.data}
    {@const failedRun = state.lastOutcome !== null && state.lastOutcome !== 'COMPLETED'}
    {@const keyBroken = state.keyStatus === 'FAILED' || state.keyStatus === 'EXPIRED'}
    <p class="state">
      {#if health}<span class="m3-label-large status"
          ><StatusShape tone={health.tone} />{health.label}</span
        >{/if}
      {#if state.lastStartedAt}
        <span class="m3-body-small m3-muted">
          Запуск {formatDateTime(state.lastStartedAt)}{state.lastTrigger
            ? ` · ${RUN_TRIGGERS[state.lastTrigger]}`
            : ''}
        </span>
      {/if}
    </p>
    {#if !state.running && failedRun && state.lastError}
      <code class="m3-mono m3-body-small error">{state.lastError}</code>
    {/if}
    {#if state.keyStatus === 'MISSING' || keyBroken}
      <p class="m3-card warning notice">
        <Icon name="key" size={20} />
        <span>{keyBroken ? 'Ключ Gemini не принят' : 'Ключ Gemini не задан'}</span>
        <a href={href('/admin/system')}>Ключи и доступы</a>
      </p>
    {/if}
    <dl class="stats">
      <div>
        <dt>готовы</dt>
        <dd class="m3-num">{formatNumber(state.ready)}</dd>
      </div>
      <div>
        <dt>в очереди</dt>
        <dd class="m3-num">{formatNumber(state.pending)}</dd>
      </div>
      <div>
        <dt>ошибки</dt>
        <dd class="m3-num">{formatNumber(state.failed)}</dd>
      </div>
      <div>
        <dt>скрыты</dt>
        <dd class="m3-num">{formatNumber(state.hidden)}</dd>
      </div>
      <div>
        <dt>запросов за {formatDay(state.budgetDay)}</dt>
        <dd class="m3-num">
          {formatNumber(state.budgetUsed)} из {formatNumber(state.dailyBudget)}
        </dd>
      </div>
    </dl>
    {#if state.lastFinishedAt}
      <p class="m3-body-small m3-muted last">
        Последний запуск: построено {formatNumber(state.lastGenerated)}, отклонено
        {formatNumber(state.lastFailed)}, запросов {formatNumber(state.lastRequests)}
      </p>
    {/if}
  {:else if summaries.error}
    <LoadError
      error={summaries.error}
      title="Не удалось загрузить сводки"
      onretry={() => summaries.load()}
    />
  {:else}
    <LoadingIndicator label="Загружаем сводки" />
  {/if}
</section>

{#if confirming}
  <ConfirmDialog
    title="Пересчитать сводки?"
    text="Только преподаватели с изменившимися отзывами. Осталось запросов сегодня: {formatNumber(
      remaining,
    )}."
    confirmLabel="Пересчитать"
    onconfirm={start}
    oncancel={() => (confirming = false)}
  />
{/if}

<style>
  .head {
    display: flex;
    flex-wrap: wrap;
    align-items: flex-start;
    justify-content: space-between;
    gap: 8px 16px;
    margin-bottom: 12px;
  }
  .head h2 {
    margin: 0;
  }
  .model {
    margin: 4px 0 0;
  }
  .state {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 4px 16px;
    margin: 0 0 12px;
  }
  .status {
    display: inline-flex;
    align-items: center;
    gap: 8px;
  }
  .error {
    display: block;
    margin-bottom: 12px;
    overflow-wrap: anywhere;
    color: var(--md-error);
  }
  .notice {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 8px 12px;
    margin: 0 0 16px;
    padding: 12px 16px;
  }
  .notice a {
    color: inherit;
    font: var(--md-label-large);
  }
  .stats {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(120px, 1fr));
    gap: 16px;
    margin: 0;
  }
  .stats div {
    display: flex;
    flex-direction: column-reverse;
    justify-content: flex-end;
    gap: 2px;
  }
  dd {
    margin: 0;
    font: var(--md-headline-small);
  }
  dt {
    font: var(--md-body-small);
    color: var(--md-on-surface-variant);
  }
  .last {
    margin: 16px 0 0;
  }
</style>

// web/src/features/reviews/SummariesCard.tsx
import { useState } from 'react';
import { Link } from 'react-router';
import { errorText } from '../../api/errors';
import {
  Badge,
  Button,
  Card,
  CardHeader,
  ConfirmDialog,
  ErrorState,
  formatDate,
  formatDateTime,
  formatNumber,
  Icon,
  LoadingIndicator,
  Stat,
  useSnackbars,
} from '../../ui';
import { useAiSummaries, useReloadTeachersAfterRun, useStartAiSummaries } from './api';
import { SUMMARY_OUTCOMES } from './labels';
import styles from './ReviewsPage.module.css';
import type { AiSummariesState } from './types';

const TRIGGERS = { SCHEDULE: 'по расписанию', ADMIN: 'администратором' } as const;

export function SummariesCard() {
  const summaries = useAiSummaries();
  useReloadTeachersAfterRun(summaries.data?.running);
  const model = summaries.data?.model;
  return (
    <Card as="section" aria-label="ИИ-сводки">
      <CardHeader
        title="ИИ-сводки"
        subtitle={model && `Gemini · ${model}`}
        actions={summaries.data && <StartButton state={summaries.data} />}
      />
      {summaries.isPending ? (
        <LoadingIndicator compact label="Загружаем сводки" />
      ) : summaries.isError ? (
        <ErrorState
          compact
          title="Не удалось загрузить сводки"
          description={errorText(summaries.error, 'Попробуйте ещё раз.')}
          onRetry={() => void summaries.refetch()}
          retrying={summaries.isFetching}
        />
      ) : (
        <SummariesView state={summaries.data} />
      )}
    </Card>
  );
}

function remaining(state: AiSummariesState): number {
  return Math.max(0, state.dailyBudget - state.budgetUsed);
}

function StartButton({ state }: { state: AiSummariesState }) {
  const snackbars = useSnackbars();
  const start = useStartAiSummaries();
  const [confirming, setConfirming] = useState(false);
  const submit = () =>
    start.mutate(undefined, {
      onSuccess: () => setConfirming(false),
      onError: (error) => {
        setConfirming(false);
        snackbars.error(
          errorText(error, 'Не удалось запустить пересчёт', {
            business_rule_violation: 'Пересчёт уже идёт',
          }),
        );
      },
    });
  return (
    <>
      <Button
        icon="auto_awesome"
        loading={state.running || (start.isPending && !confirming)}
        disabled={!state.enabled || state.keyStatus === 'MISSING'}
        onClick={() => setConfirming(true)}
      >
        Пересчитать всё
      </Button>
      <ConfirmDialog
        open={confirming}
        onClose={() => setConfirming(false)}
        onConfirm={submit}
        loading={start.isPending}
        title="Пересчитать сводки?"
        description={`Только преподаватели с изменившимися отзывами. Осталось запросов сегодня: ${formatNumber(remaining(state))}.`}
        confirmLabel="Пересчитать"
      />
    </>
  );
}

function RunState({ state }: { state: AiSummariesState }) {
  if (!state.enabled) return <Badge icon="block">Выключены на сервере</Badge>;
  if (state.running) {
    return (
      <Badge tone="info" icon="auto_awesome">
        Идёт пересчёт
      </Badge>
    );
  }
  if (!state.lastOutcome) return <Badge>Ещё не запускался</Badge>;
  const outcome = SUMMARY_OUTCOMES[state.lastOutcome];
  return <Badge tone={outcome.tone}>{outcome.label}</Badge>;
}

function KeyNotice({ state }: { state: AiSummariesState }) {
  const failed = state.keyStatus === 'FAILED' || state.keyStatus === 'EXPIRED';
  if (state.keyStatus !== 'MISSING' && !failed) return null;
  return (
    <p className={styles.notice}>
      <Icon name="key" size={20} />
      <span>{failed ? 'Ключ не принят' : 'Ключ Gemini не задан'}</span>
      <Link to="/admin/system">Учётные данные</Link>
    </p>
  );
}

function SummariesView({ state }: { state: AiSummariesState }) {
  const failed = state.lastOutcome !== null && state.lastOutcome !== 'COMPLETED';
  return (
    <div className={styles.body}>
      <p className={styles.state}>
        <RunState state={state} />
        {state.lastStartedAt && (
          <span>
            Запуск {formatDateTime(state.lastStartedAt)}
            {state.lastTrigger && ` · ${TRIGGERS[state.lastTrigger]}`}
          </span>
        )}
      </p>
      {!state.running && failed && state.lastError && (
        <code className={styles.error}>{state.lastError}</code>
      )}
      <KeyNotice state={state} />
      <div className={styles.tiles}>
        <Stat icon="check_circle" label="Готовы" value={formatNumber(state.ready)} />
        <Stat icon="schedule" label="В очереди" value={formatNumber(state.pending)} />
        <Stat icon="error" label="Ошибки" value={formatNumber(state.failed)} />
        <Stat icon="visibility_off" label="Скрыты" value={formatNumber(state.hidden)} />
        <Stat
          icon="data_usage"
          label="Запросов сегодня"
          value={`${formatNumber(state.budgetUsed)} из ${formatNumber(state.dailyBudget)}`}
          caption={formatDate(state.budgetDay)}
        />
      </div>
      {state.lastFinishedAt && (
        <p className="m3-muted">
          Последний запуск: построено {formatNumber(state.lastGenerated)}, отклонено{' '}
          {formatNumber(state.lastFailed)}, запросов {formatNumber(state.lastRequests)}
        </p>
      )}
    </div>
  );
}
